// Package go_main is an autogenerated binder stub for package main.
//
// File is generated by gobind. Do not edit.
package go_main

import (
	"crtaci"
	"golang.org/x/mobile/bind/seq"
)

func proxy_Extract(out, in *seq.Buffer) {
	param_service := in.ReadUTF16()
	param_videoId := in.ReadUTF16()
	res, err := main.Extract(param_service, param_videoId)
	out.WriteUTF16(res)
	if err == nil {
		out.WriteUTF16("")
	} else {
		out.WriteUTF16(err.Error())
	}
}

func proxy_List(out, in *seq.Buffer) {
	res, err := main.List()
	out.WriteUTF16(res)
	if err == nil {
		out.WriteUTF16("")
	} else {
		out.WriteUTF16(err.Error())
	}
}

func proxy_ListenAndServe(out, in *seq.Buffer) {
	param_bind := in.ReadUTF16()
	main.ListenAndServe(param_bind)
}

func proxy_Search(out, in *seq.Buffer) {
	param_query := in.ReadUTF16()
	res, err := main.Search(param_query)
	out.WriteUTF16(res)
	if err == nil {
		out.WriteUTF16("")
	} else {
		out.WriteUTF16(err.Error())
	}
}

func init() {
	seq.Register("main", 1, proxy_Extract)
	seq.Register("main", 2, proxy_List)
	seq.Register("main", 3, proxy_ListenAndServe)
	seq.Register("main", 4, proxy_Search)
}
