package crtaci

import (
	"regexp"
)

var (
	reTitle = regexp.MustCompile(`[0-9A-Za-zžćčšđ_,]+`)
	reAlpha = regexp.MustCompile(`[A-Za-zžćčšđ]+`)
	reDesc  = regexp.MustCompile(`(?U)(\(|\[).*(\)|\])`)
	reYear  = regexp.MustCompile(`(19\d{2}|20\d{2})`)
	reExt   = regexp.MustCompile(`\.(?i:avi|mp4|flv|wmv|mpg|mpeg|mpeg4)$`)
	reRip   = regexp.MustCompile(`(?i:xvid)?(tv|dvd)?(-|\s)(rip)(bg)?(audio)?`)
	reChars = regexp.MustCompile(`(?i:braca grimm|i snupi [sš]ou|i snupi|charlie brown and snoopy|brzi gonzales i patak da[cč]a|patak da[cč]a i brzi gonzales|patak da[cč]a i elmer|patak da[cč]a i gicko prasi[cć]|i hello kitty|tom and jerry|tom i d[zž]eri [sš]ou|spongebob squarepants|paja patak i [sš]ilja|bini i sesil|masha i medved|elmer fudd|blinkibil|kockalone|najlepse bajke|stari sinhronizovani crtaci|popeye the sailor|kasper i drugari,|leghorn)`)
	reTime  = regexp.MustCompile(`(\d{2})h(\d{2})m(\d{2})s`)
	rePart  = regexp.MustCompile(`\s([\diI]{1,2})\.?\s?(?i:/|deo|od|part)\s?([\diI]{1,2})?\s*(?i:deo)?`)
	rePart2 = regexp.MustCompile(`\s(?i:pt)\s?(\d{1,2})\s*`)

	reTitleR     = regexp.MustCompile(`^(\d{1,2}\.?)\s?(\d{1,})?(.*)$`)
	reTitleNotEp = regexp.MustCompile(`\d{2,}\s(?i:razbojnika|sati|malih|pljeskavica)`)
	reTitle20    = regexp.MustCompile(`(\s20)`)

	reE1 = regexp.MustCompile(`(?i:epizoda|epizida|epzioda|episode|epizodas|episoda|Эпизод)\s?(\d{1,3})`)
	reE2 = regexp.MustCompile(`(\d{1,3})\.?-?\s?(?i:epizoda|epizida|epzioda|episode|epizodas|episoda)`)
	reE3 = regexp.MustCompile(`\s(?i:ep|e)\.?\s*(\d{1,3})`)
	reE4 = regexp.MustCompile(`(?:^|-|\.|\s)\s?(\d{1,3}\b)`)
	reE5 = regexp.MustCompile(`(?i:s)(?:\d{1,2})(?i:e)(\d{2})(?:\d{1})?(?:a|b)`)
	reE6 = regexp.MustCompile(`(?i:s)(?:\d{1,2})(?:e)(\d{1,2})`)

	reS1 = regexp.MustCompile(`(?i:sezona|sezon)\s?(\d{1,2})`)
	reS2 = regexp.MustCompile(`(\d{1,2})\.?\s?(?i:sezona|sezon)`)
	reS3 = regexp.MustCompile(`(?i:s)\s?(\d{1,2})`)
	reS4 = regexp.MustCompile(`(\d{1,2})(?i:x)`)
)

var filters = []string{
	"najbolji crtaci",
	"www.crtani-filmovi.org",
	"by crtani svijet",
	"crtanifilmonline",
	"crtani filmovi",
	"crtani film",
	"stari crtani",
	"cijeli crtani",
	"crtani",
	"crtic",
	"sinhronizovano",
	"sihronizovano",
	"sinhronizovani",
	"sinhronizovan",
	"sinhronizacija",
	"sinkronizacija",
	"titlovano",
	"sa prevodom",
	"nove epizode",
	"na srpskom jeziku",
	"na srpskom",
	"srpska",
	"srpski",
	"srb ",
	" srb",
	" sd",
	" hq",
	" svcd",
	"hrvatska",
	"hrv,srp,bos",
	"zagorci",
	"slovenska verzija",
	"b92 tv",
	"za decu",
	"zadecu",
	"youtube",
	"youtube",
	"full movie",
	"mashini skazki",
	"the cartooner 100",
	"iz 60-70-80-tih",
	"mpeg4",
	"144p h 264 aac",
	"sihroni fll 2",
	"zlekedik",
	"gusztav allast keres",
	"guszt v k",
	"rtb",
	"tvrip",
	"djuza stoiljkovic",
	"okrenite preko smplayer-a",
	"new episodes",
	"new episode",
	"animado",
	"animad8",
	"animated",
	"cartoon",
	"of 47",
	"dailymotion-video",
	"video dailymotion",
	"ultra tv",
	"happy tv",
}

var censoredWords = []string{
	"kurac",
	"kurcu",
	"sranje",
	"sranja",
	"govna",
	"govno",
	"picka",
	"picke",
	"peder",
	"jebač",
	"uzivo",
	"parodija",
	"sprdnja",
	"tretmen",
	"ispaljotka",
	"kinder jaja",
	"video igrice",
	"atomski mravi",
	"igracke od plastelina",
	"sex",
	"sexy",
	"flesh",
	"ubisoft",
	"wanna",
	"special",
	"trailer",
	"teaser",
	"music",
	"monster",
	"intro",
	"countdown",
	"eternity",
	"summer",
	"galaxy",
	"constitution",
	"hunkyard",
	"riders",
	"flash",
	"wanted",
	"instrumental",
	"gamer",
	"remix",
	"tour",
	"party",
	"bjorke",
	"tweety",
	"revolution",
	"halloween",
	"remastered",
	"celebration",
	"experiments",
	"food",
	"gameplay",
	"surprise",
	"batters",
	"bottle",
	"erasers",
	"series",
	"comics",
	"village",
	"theatre",
	"dolphin",
	"stallone",
	"koniec",
	"latino",
	"lovers",
	"lubochka",
	"tobbe",
	"sushi",
	"prikljuchenija",
	"slovenska",
	"aakerhus",
	"sylvia",
	"deutsch",
	"remue",
	"kespar",
	"splitter",
	"desierto",
	"pelicula",
	"episodio",
	"rwerk",
	"xhaven",
	"erkste",
	"przytul",
	"potenzf",
	"szalony",
	"schweiz",
	"verkackt",
	"sottile",
	"goldene",
	"osterhase",
	"elasmosaurio",
	"ombra",
	"ehlers",
	"dejas",
	"capitulo",
	"et ses",
	"tu sais",
	"ma vision",
	"v riti ",
	"how could",
	"new year",
	" del ",
	"maldicion",
	"fernsehausstrahlung",
	"the best bits of",
	"jamella",
	"kasper-sky",
	"kasper internet",
	"feiern",
	"terpidana",
	"borba za koralovo",
	"sve pesme",
	"minecraft",
	"gasttoz",
	"gastoz",
	"batailles",
	"maminka",
	"adolphus",
	"humaine",
	"spain",
	"michele",
	"voulait",
	"cekilis",
	"igracke za decu",
	"xperiene",
	"show",
	"symphony",
	"jonathan",
	"penpanter",
	"monstruosa",
	"stationnement",
	"lightning",
	"disney",
	"children",
	"francais",
	"tryharder",
	"verstecken",
	"berlin",
	"plaudern",
	"hamburg",
	"einkauf",
	"samui",
	"chelsea",
	"norsk",
	"treffen",
	"hedgehog",
	"asteriks bend",
	"osiedle",
	"olympic games",
	"wikingowie",
	"dubbing",
	"dubbed",
	"krolewskiej",
	"brytanii",
	"britanyada",
	"kontra cezar",
	"twelve tasks",
	"ameryk",
	"animerade",
	"en cleopatra",
	"film pl",
	"cecilio",
}

var censoredIds = []string{
	"52vfFeJERfQ",
	"DLk4SLmIDUU",
	"VsNOHQfm02M",
	"yfYfGnCVbHs",
	"8zZ6tg2LXiM",
	"-1CnR5qVh5E",
	"DPxb3-7lakw",
	"zKhPpVTUn_Q",
	"vBggIcqV1rc",
	"YrmKYtDnthk",
	"YzqWmqeR43I",
	"Id3kHQC9vPI",
	"Ngke-HPnHok",
	"7VPtdqnHxHw",
	"Q6hTJ11ZGwU",
	"n28-lRu5cpw",
	"dl_kPk276oo",
	"YsdOt6qc6o4",
	"Tm7mOlgPlxA",
	"X8BwFSHJpg4",
	"QYrsrjgGh5g",
	"_z6pgpPDXBY",
	"7_ys2vKapLg",
	"G7SnbTCsj28",
	"2LzVPEoiacY",
	"8QJozzsvPnU",
	"KpLrIWB78sQ",
	"CuV0mDu4GL4",
	"c1-ywGJfS8U",
	"sotlkpiczWk",
	"wPUhMP7aGnw",
	"AR0Jc1rh2N0",
	"xuGex-B3GbQ",
	"drEJEbHDgIA",
	"JF4qkkgQsO4",
	"Y4r7m-Payv8",
	"0HDbPXN-HaE",
	"yONB3IwxtlQ",
	"BjtFDLOmEu8",
	"cpF73znG7UM",
	"2onSjJVgtpg",
	"gRLppbNNCLI",
	"smKnRR0ouds",
	"5nElGb8odmk",
	"xs_IiToWEEs",
	"co4B3-BwcUY",
	"QCHSP32z2nc",
	"CRyDcmPHZy4",
	"YyFNnHlDgP0",
	"uVn9vpFlljE",
	"LuYPcHVsyow",
	"6sPavaRoEA8",
	"JpG72eCdmKo",
	"XL4TZVlGc3o",
	"bAeHz5miEJg",
	"6zCKejl_1bY",
	"Ragr70eHvQg",
	"7nDvQPYJpMg",
	"jYU_doi3Y7w",
	"5FqM9elA3AY",
	"3Wha_dlJ9G0",
	"bTLVcWEtk-0",
	"WIqCOdLvDBs",
	"x5-SgQVUY-c",
	"MQPLlgJkvLc",
	"Fu88sn45nlE",
	"0Uq52kdn-MA",
	"9sMBmQNPFTA",
	"AiUBMthSJ9I",
	"jAsHYIyp9fY",
	"8nWgj3tk0kg",
	"2lD_oXT4ssA",
	"iT4ZXYso2kA",
	"fuYMMWpRjkM",
	"qgSiTwWVRlQ",
	"9CtO4IlBrtM",
	"cD5nttAuRM",
	"TzZ2e_CsbAg",
	"z4pecRAGn3k",
	"U8MqpWcX7m8",
	"veag9KGlq2I",
	"bcofMgTMsU4",
	"j5Wvu54nGBE",
	"HB0iJ6lYr-k",
	"rqKMr6a1Flg",
	"4MDkQHRIaSY",
	"zIPgQUhmctg",
	"iPW_Mx1VZm0",
	"B2TAIj5YgtQ",
	"38BQAuxi1Eo",
	"oVh4Vw-Qa28",
	"mrz6T7kapDo",
	"29adS3crcAg",
	"wrmxMoRGd_A",
	"sTvvLO-NeT4",
	"ZDMyeMzPBNg",
	"UiERZEoB-sA",
	"tRt4U4YbQYI",
	"_2TnyqqDIok",
	"0ukfnPyz3fo",
	"LZ6KxVxyQtY",
	"0ukfnPyz3fo",
	"BQG9cduTCXg",
	"RsAVnXbXjK4",
	"XPyoxfw2Bl8",
	"Pj6wV0ns8h4",
	"xy53o1",
	"xy53q1",
	"x3osiz",
	"x25ja2c",
	"x4aha4",
	"x7k5hx",
	"x60rr7",
	"x7k5ko",
	"x4e7mn",
	"xs4jyr",
	"x7wviw",
	"x5nyjf",
	"x20uqv5",
	"x20uvfy",
	"x29i8ae",
	"x2k0tnk",
	"x2etl16",
	"x2dv1ec",
	"x196m5x",
	"x2cz5es",
	"x2p0jt2",
	"x2r0sas",
	"x33bdoj",
	"x3vxpa_",
	"x4q5ria",
	"x2w44gk",
	"x2xw9zp",
	"4562474",
	"x4m2gx3",
	"x4gxo5k",
	"x3wlkj0",
	"21508130",
	"14072389",
	"145041047",
	"163980203",
	"165572645",
	"168855693",
	"61534934",
	"15376700",
	"73551241",
	"80060489",
	"185160199",
}
